#!/usr/bin/env python3
"""Export the phone web console into the packaged Chrome extension.

Run after changing web/index.html or h264-player.js. --check reports stale
extension assets without writing them.
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "app/src/main/assets/web"
EXT = ROOT / "chrome-extension"


def replace_once(text, old, new):
    if text.count(old) != 1:
        raise ValueError(f"Expected one console anchor: {old.splitlines()[0]}")
    return text.replace(old, new, 1)


def export():
    html = (WEB / "index.html").read_text()
    scripts = list(re.finditer(r"<script>\s*(.*?)\s*</script>", html, re.S))
    if len(scripts) != 1:
        raise ValueError("Expected one inline console script")
    script = scripts[0].group(1)
    script = replace_once(script, "function apiUrl(path) {", """// Extension pages address the selected device, not chrome-extension://.
const hostParam = new URLSearchParams(location.search).get("host") || "";
const deviceHost = hostParam.replace(/^https?:\\/\\//, "").replace(/\\/.*$/, "");
const DEVICE_ORIGIN = deviceHost
  ? (hostParam.startsWith("https://") ? "https://" : "http://") +
    (deviceHost.includes(":") ? deviceHost : deviceHost + ":8888")
  : "";
function deviceUrl(path) { return DEVICE_ORIGIN ? DEVICE_ORIGIN + "/" + path.replace(/^\\//, "") : path; }

function apiUrl(path) {
  path = deviceUrl(path);""")
    script = replace_once(script, 'fetch("api/auth/status",', 'fetch(deviceUrl("api/auth/status"),')
    script = replace_once(
        script,
        'fetch("api/auth/verify?token=" + encodeURIComponent(t),',
        'fetch(deviceUrl("api/auth/verify?token=" + encodeURIComponent(t)),',
    )
    script = replace_once(script, 'fetch("api/pair",', 'fetch(deviceUrl("api/pair"),')
    script = replace_once(script, "function wsBase() {", """function wsBase() {
  if (DEVICE_ORIGIN) return DEVICE_ORIGIN.replace(/^http/, "ws");""")
    html = html[:scripts[0].start()] + '<script src="app.js"></script>' + html[scripts[0].end():]
    html = replace_once(html, '<script src="/h264-player.js"></script>', '<script src="h264-player.js"></script>')
    header = "// Generated by scripts/sync-chrome-console.py; edit web/index.html instead.\n"
    return {
        EXT / "console.html": html.encode(),
        EXT / "app.js": (header + script + "\n").encode(),
        EXT / "h264-player.js": (WEB / "h264-player.js").read_bytes(),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in export().items():
        if args.check:
            if not path.exists() or path.read_bytes() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_bytes(content)
            print(f"Updated {path.relative_to(ROOT)}")
    if stale:
        print("Chrome console assets are stale: " + ", ".join(stale), file=sys.stderr)
        return 1
    if args.check:
        print("Chrome console assets match the web console")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
