#!/usr/bin/env python3
"""Mirror the AndroMeld panel (app/src/main/assets/web) into the packaged Chrome
extension (chrome-extension/), byte-for-byte.

The extension entry keeps the `console.html?host=...` contract, so the panel is
mirrored to the extension ROOT (not a subdirectory): the shell resolves the
Fusion window route with `new URL("window/index.html", document.baseURI)`, which
only lands on the mirrored `window/index.html` when the entry sits at the root.

Only two renames/skips are unavoidable:
  * index.html  -> console.html   (extension entry keeps the ?host= contract)
  * sw.js is dropped: an MV3 extension page is already a secure context and
    service-worker caching would shadow the adapted shell. The shell still asks
    for `./sw.js`, but that call sits behind `window.__blindcastLocal`, which
    local-adapter.js sets before the shell module runs, so it never fires here.

`manifest.webmanifest` is mirrored like everything else even though an extension
page never installs as a PWA: both mirrored pages link `/manifest.webmanifest`,
and a dropped file would leave that link 404ing on every panel load.

Everything else (css/, js/, img/, window/, icons, h264-player.js) is mirrored
1:1 so the extension and the LAN web entry run the same code.

Cleanup is scoped to panel-owned paths (MANAGED_DIRS + the panel's own root
files); extension-only files (manifest.json, popup.*, icons/) are never touched.

Run:  python3 scripts/sync-chrome-console.py [--check]
"""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "app/src/main/assets/web"
EXT = ROOT / "chrome-extension"

# Files that must not be copied verbatim (name or policy reasons).
SKIP = {"sw.js"}
# Only the extension entry (root index.html) is renamed. window/index.html is a
# separate entry and must keep its name or the Fusion window route breaks.
RENAME = {Path("index.html"): Path("console.html")}

# Directories the panel owns inside the extension root (mirrored 1:1).
MANAGED_DIRS = {"css", "js", "img", "window"}

HEADER = "<!-- Generated by scripts/sync-chrome-console.py; edit app/src/main/assets/web/index.html instead. -->\n"


def plan():
    """Yield (src, dst) for every file that should exist in the extension."""
    for src in sorted(WEB.rglob("*")):
        if not src.is_file():
            continue
        rel = src.relative_to(WEB)
        if rel.name in SKIP:
            continue
        yield src, EXT / RENAME.get(rel, rel)


def root_names():
    """Names the panel owns at the extension root (for scoped cleanup)."""
    return {
        RENAME.get(Path(p.name), Path(p.name)).name
        for p in WEB.iterdir()
        if p.is_file() and p.name not in SKIP
    }


def rendered(src, dst_name):
    """Bytes to write for dst_name: source plus the generated header for the
    extension entry. write and --check share this so they cannot disagree."""
    data = src.read_bytes()
    if dst_name == "console.html":
        header = HEADER.encode("utf-8")
        if not data.startswith(header):
            data = header + data
    return data


def is_managed(rel):
    """True when rel is a path the panel owns (safe to clean up)."""
    if rel.parts[0] in MANAGED_DIRS:
        return True
    return len(rel.parts) == 1 and rel.name in root_names()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    wanted = {dst: src for src, dst in plan()}

    if not args.check:
        # Remove panel-owned files that are no longer part of the panel.
        for existing in sorted(EXT.rglob("*"), reverse=True):
            rel = existing.relative_to(EXT)
            if existing.is_file() and is_managed(rel) and existing not in wanted:
                existing.unlink()
                print(f"Removed {rel}")
            elif (
                existing.is_dir()
                and rel.parts
                and rel.parts[0] in MANAGED_DIRS
                and not any(existing.iterdir())
            ):
                existing.rmdir()

    stale = []
    for dst, src in sorted(wanted.items()):
        expected = rendered(src, dst.name)
        if args.check:
            if not dst.exists() or dst.read_bytes() != expected:
                stale.append(str(dst.relative_to(ROOT)))
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_bytes(expected)
        print(f"Synced {dst.relative_to(ROOT)}")

    if args.check:
        if stale:
            print("Chrome extension is stale: " + ", ".join(stale), file=sys.stderr)
            return 1
        print("Chrome extension matches app/src/main/assets/web")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
